name: Build API Docs

on:
  workflow_dispatch:

jobs:
  call-doc-build-workflow:
    uses: JarrodCTaylor/build.ci/.github/workflows/doc-build.yml@master
    with:
      project: JarrodCTaylor/data.fressian
